00

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -1,32 +1,26 @@
 #!/usr/bin/env bash
-# install load balancer
+# This script installs and configures HAProxy as a load balancer.
 
+# Exit immediately if a command exits with a non-zero status.
+set -e
 
-echo -e "Updating and doing some minor checks...\n"
+# Check if HAProxy is installed, install if not
+if ! command -v haproxy &> /dev/null; then
+    echo "HAProxy not found, installing..."
+    sudo apt-get update
+    sudo apt-get install -y haproxy
+else
+    echo "HAProxy is already installed."
+fi
 
-function install() {
-	command -v "$1" &> /dev/null
+echo -e "\nPreparing configuration...\n"
 
-	#shellcheck disable=SC2181
-	if [ $? -ne 0 ]; then
-		echo -e "	Installing: $1\n"
-		sudo apt-get update -y -qq && \
-			sudo apt-get install -y "$1" -qq
-		echo -e "\n"
-	else
-		echo -e "	${1} is already installed.\n"
-	fi
-}
+# Backup the existing HAProxy configuration file for safety
+echo "Backing up the default HAProxy configuration file."
+sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_default.backup
 
-install haproxy #install haproxy
-
-echo -e "\nSetting up some minor stuff.\n"
-
-# backup default server config file
-sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup
-
-server_config=\
-"
+# Define the new HAProxy configuration
+server_config="
 defaults
   mode http
   timeout client 15s
@@ -44,20 +38,23 @@ backend clickviral-tech-backend
     server 421599-web-02 52.91.154.11:82 check
 "
 
-# shellcheck disable=SC2154
-echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg
+# Apply the new configuration
+echo "Applying new HAProxy configuration."
+echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
 
-# enable haproxy to be started by init script
-echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy
+# Ensure HAProxy is enabled to start at boot
+echo "Enabling HAProxy to start on boot."
+echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null
 
-echo "configured - Roundrobin On web-01 & web-02"
+echo "Configuration applied - Round-robin load balancing configured for web-01 and web-02."
 
+# Start or restart HAProxy to apply the new configuration
 if [ "$(pgrep -c haproxy)" -le 0 ]; then
-	sudo service haproxy start
+    echo "Starting HAProxy..."
+    sudo service haproxy start
 else
-	sudo service haproxy restart
+    echo "Restarting HAProxy..."
+    sudo service haproxy restart
 fi
 
-echo -e "web-01 web-02"
-echo "web-01"
-echo "web-02"
+echo "HAProxy setup complete."
